### ISSUE TITLE
java runtime not located... button displas java "rutnime".

### ISSUE THREAD

**Issue by JFrancisOlson** [fabioz/vscode-pydev-info#4]
![image](https://user-images.githubusercontent.com/41552324/48513865-9e780d00-e822-11e8-982a-712b49e25682.png)

I know I have java, but I keep getting this error...  noticed the spelling wrong on the button. not sure if thats related to the issue.

**Comment by ebw44** [comment]
I had the same issue for some time. In my case it was not only a pydev problem as similar problem appear with java extension. To fix it I
- installed the java jdk (I already add the jre)
- added the environment variable JAVA_HOME="C:\Program Files\Java\jdk-11.0.2"
- added "python.pydev.pythonExecutable": "C:\\Users\\DavyMoyon\\Anaconda3\\python.exe" to my vscode setting (probably because my python installation is not in my PATH).

**Comment by omstaal** [comment]
Setting JAVA_HOME did the trick for me too

**Comment by fabioz** [comment]
In 0.2.1 it's also possible to configure `python.pydev.java.home` (previous versions had a bug in that it searched for the setting `pydev.java.home`).

See: http://www.pydev.org/vscode/manual.html as a reference.
